apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: runme-replicaset
  labels:
    app: runme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: runme
  template:
    metadata:
      labels:
        app: runme
    spec:
      containers:
      - name: runme-container
        image: nginx:latest
        ports:
        - containerPort: 80
