apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  api_key: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXotLi0uLi0uLg==
  new_key: dGVzdF9uZXdfdmFsdWUtdGVzdF9uZXdfdmFsdWU=
  password: cGFzc3dvcmQxMjM=