apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: runme
stringData:
    username: runme
    password: ENC[AES256_GCM,data:TQHBz6CC+qWZEpo=,iv:Rb/aiKSfFiBmF6V0CxMecPOfaAX75FttGIttGz23Ovc=,tag:H90Jcu5RlqMQuIX4UN9VZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:655675283765:key/0f6f8f81-a341-489a-ab7d-e1ab25f003df
          context:
            Role: runme-test
          created_at: "2024-03-28T08:10:01Z"
          enc: AQICAHgRpXGnqU3uFwcTyUUcvrNMEWsl86whp1IDpj1ClE8kxgESxnn7Iyav5Gm0oyPDdWe+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlqpmyYpbn4jZbvB+AgEQgDsnl+tqMVBDoq6dI1dQVruWKhWfklbdKpp0dN8dyEpEWDwpzx7Vp4kBkIiu1ptAYaw9OzdIKx9Cnhpfrw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-28T08:10:07Z"
    mac: ENC[AES256_GCM,data:DEc20VqIqjn2v2QZbYA7Eeu/B0ztN6bWywXkyCh3Gm7HA3XgOLV9sUBuFgXeSsjBzqh+ews5uEKD6SS35gFHxNlm6GFGSEqhw5EBMUTNREwCSMnhFFf4sImkplc0HidAtZYX6tmmbdUJcFyh7ojfyqLOgPxVwkMkOLxME+LTB1Y=,iv:ae8XtZOwKWMKvKX4/Gwd5Ipn7OBfwN1/H12eou7Wq0w=,tag:UCR/yCIylYeFkASiL7wmlA==,type:str]
    pgp: []
    encrypted_regex: password
    version: 3.8.1
