apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agro-cd-demo
  template:
    metadata:
      labels:
        app: agro-cd-demo
    spec:
      containers:
      - name: agro-cd-demo
        image: python:3.9-slim
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: agro-cd-demo
spec:
  selector:
    app: agro-cd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
